# TODO release XSD to timefold.ai/xsd/
# TODO reset timefold-quickstarts stable branch
# TODO adjust website pom.yml release date and version
# TODO update version in https://timefold.ai/product/upgrade/upgrade-timefold.gradle
# TODO tag github issues with version
name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      nextVersion:
        description: 'Next version after release (-SNAPSHOT will be added automatically)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set release version
        run: mvn --no-transfer-progress --batch-mode -Dfull versions:set -DnewVersion=${{ github.event.inputs.version }}

      - name: Commit and push release version
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          message: Set release version ${{ github.event.inputs.version }}

      - name: Build stage release
        run: mvn --no-transfer-progress --batch-mode -Dfull clean deploy -DaltDeploymentRepository=local::default::file://`pwd`/target/staging-deploy

      - name: Run JReleaser
        run: mvn --no-transfer-progress --batch-mode -Dfull jreleaser:full-release -DaltDeploymentRepository=local::default::file://`pwd`/target/staging-deploy
        env:
          #          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME: ${{ secrets.JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD }}

      - name: Set snapshot version
        run: mvn --no-transfer-progress --batch-mode -Dfull versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}-SNAPSHOT

      - name: Commit and push tag and snapshot version
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          message: Set next SNAPSHOT version ${{ github.event.inputs.nextVersion }}-SNAPSHOT
          tags: true

      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
